trigger:
  - main  # Assuming your default branch is named 'main'

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'  # Use the version of Python you need

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python main.py
  displayName: 'Run Python script'
